# Generated by Django 4.1.5 on 2023-01-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField()),
                ('capacity', models.PositiveIntegerField()),
                ('current_passengers', models.PositiveIntegerField()),
                ('fare', models.FloatField()),
                ('taxi_type', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
